services:
    database:
        image: postgres
        container_name: database
        ports:
            - "${POSTGRES_PORT}:5432"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - "database-data:/var/lib/postgresql/data"
        restart: always

    adminer:
        image: adminer
        ports:
            - "8080:8080"
        depends_on:
            - database

volumes:
    database-data:
